### ISSUE TITLE
Do we need to care about other DDR speeds than 2133?

### ISSUE THREAD

**Issue by lbmeng** [starfive-tech/beagle_ddrlnit#3]
build/Makefile defines DDR_SPEED as 2133, but lists some other possible speeds

```
#DDR_SPEED 1:1600. 2:2133 3:2800 4 :3200
DDR_SPEED = 2133
```

I believe these are all supported speeds by the DDR controller on the JH7100 SoC.

When upstream, do we need to care about other possible DDR speeds the SoC supports?
Or do we plan to create board variants that have a different DRAM chip mounted with different frequency?

**Comment by pdp7** [comment]
@MichaelZhuxx could you please check with the SoC team about these questions from @lbmeng?

> When upstream, do we need to care about other possible DDR speeds the SoC supports?
> Or do we plan to create board variants that have a different DRAM chip mounted with different frequency?

**Comment by MichaelZhuxx** [comment]
Recommend only use 2133 as major DDR speed after discuss with SoC team @pdp7 @lbmeng

**Comment by lbmeng** [comment]
Thanks @MichaelZhuxx for the clarification.
