### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by tpetazzoni** [starfive-tech/beagle_ddrlnit#5]
There is no license file or license information. Some files have a BSD-3c license, some have an Apache-2.0 or GPL-2.0+ license. There is even a u-boot.bin.out file being generated, so one wonders if parts of U-Boot are being used, which would make the whole project GPL-2.0 licensed.

Could the licensing be clarified ?

**Comment by pdp7** [comment]
@yimingyiming @MichaelZhuxx could you please comment on this?

**Comment by pdp7** [comment]
There is now a license in this commit: https://github.com/starfive-tech/beagle_ddrinit/commit/cfa2230f834ab4c1ff0176ea5aebc7596bb3dfb5

@tpetazzoni does that satisfy what you were looking for?

**Comment by pdp7** [comment]
@MichaelZhuxx please add SPDX license header to all the files with StarFive copyright.  They need this:
```
/* SPDX-License-Identifier: GPL-2.0-or-later */
```

**Comment by MichaelZhuxx** [comment]
@pdp7 please check it https://github.com/starfive-tech/beagle_ddrinit/commit/82e631d844685fd146f90fd1f2925579f2811430 and also release a new binary based on your draft https://github.com/starfive-tech/beagle_ddrinit/releases/tag/ddrinit-2133-210607

**Comment by pdp7** [comment]
@MichaelZhuxx thank you for adding those SPDX headers.

I also have created a LICENSE file.  Please review PR https://github.com/starfive-tech/beagle_ddrinit/pull/9
